회원가입 기능 구현
DDu-Du-DDu-Du/back-end pull request #22
Opened 2023-12-21 20:44 UTC by IjjS

## 관련 이슈
Resolves #14 

## 구현 내용
* `V1__schema.sql`에 유저 테이블 추가
* 유저 엔티티 정의
* 이메일 검증
* 비밀번호 조건 검증 (8자리 이상 영문, 숫자, 특수문자)
* 닉네임, 선택 아이디 검증 (blank)
* 회원가입 기능 구현
* 테스트 작성
* 더미 데이터 추가

PR이 너무 커진 것 같아 죄송하네요..ㅠㅠ 엔티티를 먼저 작성하고 PR 날릴 걸 그랬습니다. 다음부턴 과하지 않도록 PR 쪼개서 올리겠습니다!

2023-12-22 11:30 UTC, uijin-j requested changes
고생한 흔적이 넘 잘 보이네요큐ㅠㅠ 고생하셨습니당!🙇🏻‍♀️
테스트 코드가 잘 작성되어 있어서 많이 배워가네용~~

저 근데 궁금한 점이 있는데, DB에 데이터를 저장하면 한국시간으로 저장이 되나요?
제가 어제 발견했는데, 한국 시간으로 저장이 안되는 것 같더라구요! 

혹시 같은 문제가 발생하신다면, 제가 아래와 같이 doker 설정을 변경하니까 해결이 되었어서 공유드립니당..(근데 이건 이번 머지보단 따로 이슈를 파야하나??)
1. `Dockerfile`에 `ENV TZ=Asia/Seoul` 추가
2. `docker-local.sh`에 
```
TZ='Asia/Seoul'
# ...

# Local DB Container
docker run --name "${CONTAINER_NAMES[0]}" \
  --health-cmd="$HEALTH_CHECK_CMD" \
  -e TZ="$TZ" \ # 이부분 추가!
  -e MYSQL_PASSWORD="$LOCAL_PASSWORD" \
  -e MYSQL_DATABASE="$LOCAL_DATABASE" \
  -d -p 13306:3306 "$IMAGE_NAME" \
  && echo "${CONTAINER_NAMES[0]} created!" \
```

2023-12-22 11:33 UTC, IjjS commented on src/main/java/com/ddudu/user/domain/Password.java
> +      throw new IllegalArgumentException("비밀번호가 입력되지 않았습니다.");
이건 임의로 정해놓은거라 아마 예외 메세지 합치면서 나중에 의논해보면 좋을 것 같네요!

2023-12-22 11:34 UTC, IjjS commented on src/main/java/com/ddudu/user/domain/User.java
> +      name = "address", column = @Column(name = "email", length = 50, nullable = false)
엥 했는데 빠졌네요..수정해놓을게요!!

2023-12-22 11:35 UTC, IjjS commented on src/main/java/com/ddudu/user/domain/User.java
> +  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
이걸 @JsonSerialize랑 @JsonDeserialize로 하는 사람들도 있던데..뭐가 더 좋은지는 천천히 찾아보겠습니다!

2023-12-22 11:44 UTC, IjjS commented on src/main/java/com/ddudu/user/domain/User.java
> +    isDeleted = false;
처음엔 필드에 바로 지정을 했었는데 나중에 다른 생성자를 사용할 수도 있지 않을까 생각이 들어서 유연하게 가져가려고 바꿨습니다!

예를 들어 나중에 이메일 인증을 추가한다면 기본적으로 상태가 `INACTIVE`겠지만 구글로그인을 이용해 회원가입이 된 회원이면 바로 `ACTIVE`가 되면 되잖아요? 그래서 일단 생성자에 포함하고 나중에 다른 케이스가 나오면 해당 생성자를 만드려고 했었는데, 생각해보니 빌더 패턴으로 `Objects.isNull(status) ? INACTIVE : ACTIVE`하는 식으로 쓸 수도 있었겠다 싶네요. 아직 빌더 패턴이 익숙하지 않아서 생각이 짧았습니다

아무튼 필드에 바로 기본값 할당 하는 것도 변경이 안 되는 것은 아니니 큰 차이는 없어 보이고 필드에 할당하면 코드도 줄어드니까 나쁘지 않은 것 같습니다! `isDefault` 같이 확실한 값은 필드로 넣어주고 나중에 `conductDeletion`같은 메서드를 넣어 바꿔주는 것도 괜찮네요. 다음 번 스키마 고민을 하면서 의논해보죠!!

2023-12-22 11:45 UTC, IjjS commented on src/main/java/com/ddudu/user/dto/request/SignUpRequest.java
> +    )
머리 좀 굴려봤습니다 후후

2023-12-22 11:46 UTC, IjjS commented on src/main/java/com/ddudu/user/service/UserService.java
> +  private static final PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
아 이것도 놓친 부분이네요, 아마 WebSecurityConfig에도 빈으로 등록돼있을텐데..수정하겠습니다!

2023-12-22 11:47 UTC, IjjS commented on src/main/java/com/ddudu/user/domain/User.java
> +  @Column(name = "optional_username", length = 20, unique = true)
rebase할 때 잘못 건드렸더니 이렇게 된 것 같습니다. 수정할게요!! 감사함다

2023-12-22 11:48 UTC, IjjS commented on src/test/java/com/ddudu/user/domain/UserTest.java
> +    }
이것도 나중에 테스트 디렉토리 밑에 별개 클래스로 빼놓을까 싶어요

2023-12-22 11:48 UTC, IjjS commented on src/test/java/com/ddudu/user/domain/UserTest.java
> +      assertThat(persistedFirst.getId()).isNotEqualTo(persistedSecond.getId());
따봉입니다. 천재세요?

2023-12-22 12:06 UTC, uijin-j commented on src/main/java/com/ddudu/user/domain/User.java
> +    isDeleted = false;
아핫 OAuth 생각을 못했네요! 확실히 `isDeleted`같이 간단한 디폴트값 지정이 아니면, 빌더에서 초기화하는 게 더 좋은 방법인 것 같습니다!
이부분은 다음 스프린트 플래닝할 때 이야기 나누거나, 일단 자기 스타일대로 하고 추후 맞춰봐도 될 것 같아용!

2023-12-22 12:08 UTC, uijin-j commented on src/main/java/com/ddudu/user/service/UserService.java
> +  private static final PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
다른 곳에서 쓸 일이 없으면 이렇게 UserService에서 초기화하는 방법 좋습니당!

2023-12-22 12:10 UTC, uijin-j approved these changes
수고하셨습니다~

2023-12-23 06:26 UTC, yenzip approved these changes
전체적으로 코드가 깔끔해서 읽기가 매우 편했습니다!
또, 테스트 코드를 꼼꼼하게 작성되어 있어서 좋았습니다!

테스트 코드를 각자 작성하다 보니, 다른 부분이 있는데 이런 부분은 추후 리팩토링할 때 맞춰나가면 좋을 것 같습니다!

고생 많으셨습니다 🥇

2023-12-23 06:26 UTC, yenzip commented on src/test/java/com/ddudu/user/service/UserServiceTest.java
> +      assertThatExceptionOfType(DuplicateKeyException.class).isThrownBy(signUp)
assertThatThrownBy 만 사용해봤는데 assertThatExceptionOfType으로도 가능하군요!
하나 배워갑니다! 👍 
두 방법 모두 개인의 취향이긴 하나 리팩토링할 때, 하나로 통일해보는 것도 좋을 것 같네요!

2023-12-23 06:26 UTC, yenzip commented on src/test/java/com/ddudu/user/controller/UserControllerTest.java
> +        .password(8, 40, false, true, true);
(8, 40, false, true, true)가 무슨 의미일까 찾아봤는데..
(최소 길이, 최대 길이, 대문자 포함 여부, 특수문자 포함 여부, 숫자 포함 여부)였군요!
Faker 배워갑니다 👍

2023-12-23 08:58 UTC, IjjS commented on src/main/resources/db/migration/V1__schema.sql
> +    is_deleted        TINYINT(1)   NOT NULL DEFAULT '0',
놓친 점이었는데, 잡아주셔서 감사해요!

2023-12-23 09:20 UTC, yenzip approved these changes
확인 완료했습니다!
고생 많으셨습니다 👍

2023-12-23 09:43 UTC, uijin-j commented on src/main/resources/db/migration/V1__schema.sql
> +    is_deleted        TINYINT(1)   NOT NULL DEFAULT '0',
매의눈..

2023-12-23 09:44 UTC, uijin-j approved these changes

2023-12-23 17:56 UTC, merged