할 일 생성 기능 구현
DDu-Du-DDu-Du/back-end pull request #60
Opened 2024-01-01 18:48 UTC by uijin-j

## 🎫관련 이슈

Resolves #59

## 🎊구현 내용

- [x]  할 일 생성 기능을 구현한다.
- [x] 할 일 생성 테스트 코드를 작성한다.

2024-01-01 19:48 UTC, IjjS reviewed
👍

2024-01-01 19:48 UTC, IjjS commented on src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
단일 목표 조회 테스트 안에 Put이 들어가있습니다. 수정 테스트가 안에서 섞인 것 같은데 제가 #47 에 이걸 반영해두긴 했습니다. 이 부분은 아예 지우시고 [여기](https://github.com/DDu-Du-DDu-Du/back-end/pull/47/commits/8a62f60579238ec79f59f7cd03d235081db5c5c1)에 코멘트 추가해주시는 건 어떨까요?

2024-01-01 19:48 UTC, IjjS commented on src/test/java/com/ddudu/todo/domain/TodoTest.java
> +      User user = createUser("코딩몬");
ㅋㅋㅋ

2024-01-02 04:41 UTC, yenzip commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +  public ResponseEntity<TodoInfo> create(
`createTodo()` 대신 `create()`로 작성하셨네요!
저도 다음 PR(#49) 에 Controller 메서드 이름 통일시키겠습니다! 👍

2024-01-02 05:10 UTC, yenzip submitted a review, later dismissed
고생 많으셨습니다 🥇 

크게 수정할 건 없고 통일하면 좋을 것들에 대해 코멘트 남겼습니다! 👍

2024-01-02 05:10 UTC, yenzip commented on src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
> +  static final Faker faker = new Faker();
Faker Todo에도 반영해주셨군요..! 👍

2024-01-02 05:10 UTC, yenzip commented on src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
> +          .build();
```suggestion
      TodoInfo response = createTodoResponse(name);
```
`createTodoInfo()` 메서드가 아래 존재하는데 활용해보는 건 어떨까요? 해당 메서드에 name 추가해도 좋을 것 같습니다..! (저도 우선 임시로 만들어 놓은거라 마음껏 활용하셔도 됩니다!)

2024-01-02 11:19 UTC, IjjS commented on src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
머지되고 반영됐습니다 ㅎㅎ 컨플릭트 조심하시면 될 것 같네요!

2024-01-02 12:50 UTC, uijin-j commented on src/test/java/com/ddudu/todo/domain/TodoTest.java
> +      User user = createUser("코딩몬");
딩몬이 출연료 받아야 돼~~ㅋㅋㄱ

2024-01-02 12:51 UTC, uijin-j commented on src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
감사합니당! 다음부터 조금 더 꼼꼼하게 보고 PR 올리겠습니다.!🙇🏻‍♀️🙇🏻‍♀️

2024-01-02 12:55 UTC, uijin-j commented on src/main/java/com/ddudu/todo/domain/Todo.java
> +    if (isNull(user)) {
매의눈! 감사합니당👀✨

2024-01-02 12:59 UTC, uijin-j commented on src/main/resources/db/migration/V1__schema.sql
>      CONSTRAINT fk_goal_id FOREIGN KEY (goal_id) REFERENCES goal (id)
제약 조건명이 중복(`fk_user_id`) 되어 발생한 에러를 해결하는데만 신경을써서 다른 fk 네이밍도 변경할 생각을 못했네요!!
바로 적용해 놓겠습니다!👍🏻

2024-01-02 13:04 UTC, uijin-j commented on src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
> +          .build();
헉 제가 실수로 놓쳤나보네요! 수정해 놓겠습니당~~

2024-01-02 15:24 UTC, IjjS requested changes
LGTM! 풀하고 다시 리뷰 요청 보내주시죠 ㅎㅎ

2024-01-02 18:09 UTC, uijin-j reviewed
merge하면서 
- todo 예외 추가 (`GOAL_NOT_EXISTING`, `USER_NOT_EXISTING`) 및 적용
- 테스트 코드에서 conflit가 많이 발생했는데, main꺼를 대부분 그대로 쓰고 제가 이번 PR에서 추가한 테스트 코드만 남겼습니다!
- 그리고 테스트 코드에서 `@Neste`d class 안에 private 메서드가 가장 상단에 있던데, 하단으로 내려줬습니다! (저는 보통 private메서드는 가장 하단에 두는데, 혹시 의도하시고 상단에 두셨던 거라면 말씀주세요!!)

2024-01-02 18:46 UTC, IjjS commented
현재 코드 스타일로 코드 자동 포매팅 하면 아마 클래스보다 메서드가 우선으로 올라오게 돼서 Nested보다 위로 올라와서 그런 것 같아요

2024-01-02 18:49 UTC, IjjS approved these changes

2024-01-02 19:20 UTC, yenzip approved these changes
고생 많으셨습니다! 👍

2024-01-02 19:21 UTC, merged