할 일 리팩토링
DDu-Du-DDu-Du/back-end pull request #66
Opened 2024-01-03 17:22 UTC by yenzip

## 🎫관련 이슈

Resolves #49 

## 🎊구현 내용

2024-01-03 19:26 UTC, IjjS approved these changes
이렇게 보니까 생각보다 리뷰 했는데도 못 보고 놓쳤던 것들이 많았네요..고생하셨습니다!

2024-01-03 19:26 UTC, IjjS commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +          CreateTodoRequest request
이런 부분을 나중에 머지할 땐 accept 안 하고 하면 괜찮을 것 같습니다!

2024-01-03 19:26 UTC, IjjS commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +  public ResponseEntity<TodoResponse> get(
뭔가 막상 get만 남으니까 아쉽긴 하네요..ㅋㅋㅋ

2024-01-03 19:26 UTC, IjjS commented on src/main/java/com/ddudu/todo/domain/Todo.java
> +@SQLRestriction("is_deleted = 0")
👍👍

2024-01-03 19:26 UTC, IjjS commented on src/test/java/com/ddudu/todo/service/TodoServiceTest.java
> +  }
🙇‍♂️👍

2024-01-03 19:26 UTC, IjjS commented on src/test/java/com/ddudu/todo/domain/TodoTest.java
> +  }
😲👍

2024-01-04 00:59 UTC, yenzip commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +          CreateTodoRequest request
merge할 때, accept 안 했는데 reformat code하면서 자동으로 변경된 것 같네요.. 😢
원인 찾아서 다시 되돌려놓겠습니다..!

2024-01-04 01:05 UTC, yenzip commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +  public ResponseEntity<TodoResponse> get(
저도 Todo를 지우고 나니까 조금 어색하더라고요..ㅎㅎ 😃
그래서 getOne을 할지 아니면 다시 Todo를 적을지 고민입니다!

2024-01-04 01:08 UTC, yenzip commented on src/test/java/com/ddudu/todo/service/TodoServiceTest.java
> +  }
코드 보니까 TodoTest와 같이 createGoal도 BeforeEach에 넣어주면 좋을 것 같다는 생각이 드네요..!

2024-01-04 01:31 UTC, IjjS commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +  public ResponseEntity<TodoResponse> get(
getById라고 하면 괜찮으려나요

2024-01-04 01:31 UTC, IjjS commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +          CreateTodoRequest request
일단 그냥 두고 담번에 해도 괜찮을 것 같아요!!

2024-01-04 01:40 UTC, yenzip commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +  public ResponseEntity<TodoResponse> get(
오! getById 좋네요..! getById로 수정하겠습니다! 
감사합니다 🙇

2024-01-04 19:31 UTC, uijin-j requested changes
리팩토링까지 바로바로 하시다닝 굳굳👍🏻👍🏻
QueryDSL 부분만 고쳐주시면 될 것 같습니당!

2024-01-04 19:31 UTC, uijin-j commented on src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
> +    @ValueSource(strings = {"invalid-date", "20231225", "2023-15-01", "2023-12-33"})
꼼꼼하시군용!👍🏻

2024-01-04 23:55 UTC, yenzip commented on src/main/java/com/ddudu/todo/repository/TodoRepositoryImpl.java
> +            todo.beginAt.lt(endDate)
user 넣어줬었는데.. conflict merge하면서 빠진 것 같네요..! 
감사합니다..! 🙇

2024-01-04 23:55 UTC, yenzip commented on src/main/java/com/ddudu/todo/repository/TodoRepositoryImpl.java
> +            todo.beginAt.between(startDate, endDate)
으아악... 빠진 부분이 많았군요.. 😢

2024-01-05 00:43 UTC, yenzip commented on src/main/resources/db/data/afterMigrate.sql
> +SET foreign_key_checks = 1;
네! 맞습니다..! 현재 상황에서는 필요하지 않지만, 추후 Like(리액션) 테이블에 Todo id가 외래키로 필요할 것 같아 미리 넣어두었습니다!

2024-01-05 00:52 UTC, yenzip commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +    List<TodoListResponse> response = todoService.findDailyTodoList(userId, date);
Daily로 끝나면, 형용사이기 때문에 개인적으로는 살짝 어색할 것 같아요.. 😅
대신 날짜별로 모든 할 일을 조회하니까 `findAllByDate`는 어떠신가요?
흠.. 다른 서비스 메서드 이름들도 적절하게 수정이 필요할 것 같네요. 한 번 수정해보겠습니다!

2024-01-05 02:51 UTC, IjjS commented on src/main/java/com/ddudu/todo/repository/TodoRepositoryImpl.java
> +import static com.ddudu.todo.domain.QTodo.todo;
뭔가 느낌적으로 얘 때문에 컴파일 에러 뜬 것 같기도 하고..

2024-01-07 05:52 UTC, uijin-j commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +    List<TodoListResponse> response = todoService.findDailyTodoList(userId, date);
`findAllByDate()` 좋은데용?

2024-01-08 20:56 UTC, yenzip reviewed
* Todo 모든 API `@Login` 적용 ([a13befe](https://github.com/DDu-Du-DDu-Du/back-end/pull/66/commits/a13befef88e2f63ce5d66c607df96b69b75ea9d9))
* 로그인 유저와 할 일의 유저를 비교하기 위해 Todo에 검사 로직 추가 ([56de92e](https://github.com/DDu-Du-DDu-Du/back-end/pull/66/commits/56de92e7e78d34fa206a25793ee6a8143f8a1dd5))
* 할 일 생성, 단일 조회, 상태 변경에 대해 로그인한 사용자와 할 일 사용자가 같지 않으면 `권한 없음` 예외 던지기 적용 완료 ([1daa8bf](https://github.com/DDu-Du-DDu-Du/back-end/pull/66/commits/1daa8bfd26c18773228749c6363ad340e0d02d55), [def67b5](https://github.com/DDu-Du-DDu-Du/back-end/pull/66/commits/def67b5a9615efe6547035d2dc2c6849a60d232b))

* 일별 조회, 주간 및 월간 달성률 조회는 다른 사람의 할 일을 조회와 합쳐서 적용하도록 하겠습니다!

2024-01-09 00:26 UTC, IjjS approved these changes

2024-01-09 00:26 UTC, IjjS commented on src/main/java/com/ddudu/todo/controller/TodoController.java
> +  public ResponseEntity<Void> delete(
👍

2024-01-09 00:26 UTC, IjjS commented on src/main/java/com/ddudu/todo/domain/Todo.java
> +  public boolean isCreatedByUser(Long userId) {
👍👍

2024-01-09 05:17 UTC, uijin-j approved these changes
LGTM~~

2024-01-09 05:23 UTC, merged